"""Added autoincrement to tables primary key

Revision ID: 1c3a39548b50
Revises: a5c57865d94c
Create Date: 2023-07-04 18:09:02.213369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3a39548b50'
down_revision = 'a5c57865d94c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
