"""Added relationships to Fav and Brand models

Revision ID: 4ad96ead5bee
Revises: 8bc554202e74
Create Date: 2023-07-04 00:34:24.310643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad96ead5bee'
down_revision = '8bc554202e74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
