"""Added relationships to Fav and Brand models tekrardan

Revision ID: a5c57865d94c
Revises: 4ad96ead5bee
Create Date: 2023-07-04 00:45:39.930478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c57865d94c'
down_revision = '4ad96ead5bee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
